# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetti-face-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: olivetti-face-app
  template:
    metadata:
      labels:
        app: olivetti-face-app
    spec:
      containers:
        - name: olivetti-face-app
          image: g24ai2093/olivetti-face-app:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: olivetti-face-service
spec:
  selector:
    app: olivetti-face-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
